version: 4.2.0.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

skip_commits:
  files:
    - doc/**/*
    - docs/**/*
    - '**/*.html'

image:
  - Visual Studio 2017

build: off
test: off

artifacts:
  - path: artifacts/*.*nupkg
    name: Packages
  
build_script:
  - ps: .\Build.ps1

deploy:
- provider: NuGet
  name: Prerelease
  api_key:
    secure: OxGFtmO9BbWN4+be0SkCVwoRmwyES/Ve7k/wufyQfvG+dEZkaXSjKnnoolk9yktn
  on:
    branch: develop
- provider: NuGet
  name: Release
  api_key:
    secure: OxGFtmO9BbWN4+be0SkCVwoRmwyES/Ve7k/wufyQfvG+dEZkaXSjKnnoolk9yktn
  on:
    branch: master
